export const testBooks = [
  {
    id: 1,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkein',
    pages: '1241',
    available: 'No',
    overdue: 'No',
  },
  {
    id: 2,
    title: 'Oddyssey',
    author: 'Homer',
    pages: '384',
    available: 'No',
    overdue: 'Yes',
  },
  {
    id: 3,
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    pages: '71',
    available: 'Yes',
    overdue: 'No',
  },
  {
    id: 4,
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    pages: '71',
    available: 'Yes',
    overdue: 'No',
  },
  {
    id: 5,
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    pages: '71',
    available: 'Yes',
    overdue: 'No',
  },
  {
    id: 6,
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    pages: '71',
    available: 'Yes',
    overdue: 'No',
  },
  {
    id: 7,
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    pages: '71',
    available: 'Yes',
    overdue: 'No',
  },
  {
    id: 8,
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    pages: '71',
    available: 'Yes',
    overdue: 'No',
  },
  {
    id: 9,
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    pages: '71',
    available: 'Yes',
    overdue: 'No',
  },
];